
const productos =[
    {
        "id": 1,
        "producto": "anillo",
        "precio": 47000,
        "descripcion": "oro 18 kilates",
        "oferta": true,
    },
    { "id": 2,
        "producto": "collar",
        "precio": 7000,
        "descripcion": "plata 825",
        "oferta": false,
    },
    { 
        "id":3,  
        "producto": "colgante",
        "precio": 9000,
        "descripcion": "colgante con forma de corazon",
        "oferta": true,
    },
    { 
        "id": 4,
        "producto":"pulsera",
        "precio": 5500,
        "descripcion": "pulsera de oro",
        "oferta": false,
    },
    { "id":5,
        "producto": "reloj",
        "precio": 6500,
        "descripcion": "reloj pulsera",
        "oferta": false,
    },
    {   
        "id":6,
        "producto":"aros",
        "precio": 7500,
        "descripcion": "aros redondos",
        "oferta": false,
    },
    { "id":7,
        "producto":"alianzas oro",
        "precio": 45000,
        "descripcion":"alianzas oro 18 kilates",
        "oferta":false,
    },
    { "id":8,
        "producto":"alianzas plata",
        "precio": 14000,
        "descripcion":"alianzas de plata 825",
        "oferta": false,
    },
    {   "id":9,
        "producto":"abridores",
        "precio": 11500,
        "descripcion":"abridores perlita",
        "oferta":false,
    },
    {   "id":10,
        "producto": "cadena con inicial",
        "precio": 4800,
        "descripcion": "cadena con dije inicial",
        "oferta": false,
    },
    {   "id":11,
        "producto":"cadena con corazon",
        "precio": 6990,
        "descripcion":"cadena plata 925",
        "oferta":false,
    },
    { "id":12,
        "producto": "dije huella",
        "precio": 2360,
        "descripcion":"dije con huella de perrito",
        "oferta": false,
    },
    { "id":13,
        "producto":"anillo compromiso",
        "precio": 48000,
        "descripcion":"compromiso casamiento dama",
        "oferta":false,
    },
    { "id":14,
        "producto": "anillo sello",
        "precio": 53000,
        "descripcion": "anillo 18 kts sello oval",
        "oferta": false,
    },
    { "id":15,
        "producto":"anillo con grabado",
        "precio": 9000,
        "descripcion":"anillo con grabado personalizado",
        "oferta":false,
    },
]
